test_website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from userLogin import views

urlpatterns = [
	# url(r'^$', views.index, name = 'index'),
    url(r'^admin/', admin.site.urls),
    url(r'^userLogin/', include('userLogin.urls'))
]

userLogin/urls.py
from django.conf.urls import url
from userLogin import views

app_name = 'userLogin'

urlpatterns = [
	# url(r"^$", views.index, name = 'index'),
	url(r'^$', views.index, name = 'index'),
	url(r'^form/', views.register, name = 'form'),
	url(r'^thanku/', views.thank_you, name = 'thank_you'),
	url(r'^logout/', views.user_logout, name = 'user_logout'),
	url(r'^login/', views.user_login, name = 'user_login'),
]

userLogin/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class user_obj(models.Model):
	# name = models.CharField(max_length = 264)
	# email = models.EmailField(max_length = 264, unique = True)

	user = models.OneToOneField(User)

	# Additional parameters
	nick_name = models.CharField(max_length = 100)
	profile_pic = models.ImageField(upload_to = 'profile_pics', blank = True)

	def __str__(self):
		return self.user.username

userLogin/forms.py
from django import forms
from django.contrib.auth.models import User
from userLogin.models import user_obj


class user_form(forms.ModelForm):

	# name = forms.CharField()
	# email = forms.EmailField()

	passsword = forms.CharField(widget = forms.PasswordInput())

	class Meta():
		model = User
		fields = ('username', 'email', 'passsword')

class user_profile_info_form(forms.ModelForm):
	class Meta():

		# The model is user_obj 
		model = user_obj
		# Doubt at this step
		# My guess is that we want to only extract these two field from the form 
		fields = ('profile_pic', 'nick_name')

userLogin/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required	

from userLogin.forms import user_form, user_profile_info_form
from userLogin.models import user_obj
from django.contrib.auth.models import User
# Create your views here.

def index(request):
	return render(request, 'userLogin/index.html')

@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('userLogin:index'))

def register(request):
	registered = False

	if request.method == 'POST'	:
		userForm = user_form(data = request.POST)
		userProfileInfoForm = user_profile_info_form(data = request.POST)

		if userForm.is_valid() and userProfileInfoForm.is_valid():
			user = userForm.save()
			user.set_password(user.password)

			user_profile = userProfileInfoForm.save(commit = False)
			user_profile.user = user

			if 'profile_pic' in request.FILES:
				user_profile.profile_pic = request.FILES['profile_pic']

			user_profile.save()
			# print('SAVED................................')
			registered = True

		else:
			print(userForm.errors, userProfileInfoForm.errors)
	else:
		userForm = user_form()
		userProfileInfoForm = user_profile_info_form()

	return render(request, 'userLogin/form.html', {'user_form':userForm, 'profile_form':userProfileInfoForm,
		'registered':registered})




def user_login(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(username = username, password = password)

		if user:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect(reverse('userLogin:index'))
			else:
				return HttpResponse('ACCCOUNT NOT ACTIVE')
		else:
			print('An attempt to login failed ..........')
			print('username: {}  password: {}'.format(username, password))
			return HttpResponse('Invalid login details supplied')
	else:
		return render(request, 'userLogin/login.html', {})

def thank_you(request):
	return render(request, 'userLogin/thanku.html',)

templates/userLogin/form.html
<!DOCTYPE html>
{% extends 'userLogin/index.html' %}

{% block body_block %}
<div class = 'container'>
	<div class = 'jumbotron'>
		{% if registered %}
			<h2>Thank you for registering.</h2>
		{% else %}
			<h1>Register Here!</h1>
			<h3>Fill the form</h3>
			<form enctype="multipart/form-data" method = 'post'>
				{% csrf_token %}
				{{ user_form.as_p }}
				{{ profile_form.as_p }}
				<input type="submit" name="Register" value = 'Register'>
			</form>
		{% endif %}
	</div>
</div>
{% endblock %}

<!-- <!DOCTYPE html>
<html>
<head>
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<title>Forms</title>
</head>
<body>
	<dir class = 'container'>
		<form method="POST">
			{{ form.as_p }}	
			{% csrf_token %}
			<input type="submit" class = "btn btn-primary" value="Submit">
		</form>
		
	</dir>
<a href = "{% url 'userLogin:index' %}">Link for home page</a>
</body>
</html> -->

templates/userLogin/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href='{% static "userLogin/css/index.css" %}'/>
	<title>Hello</title>
</head>
<body>
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <a class="navbar-brand" href="#">Agspert</a>
	    </div>
	    <ul class="nav navbar-nav">
	      <li><a href="{% url 'userLogin:index' %}">Home</a></li>
	      <li><a href="{% url 'userLogin:form' %}">Register</a></li>
	      <li><a href="{% url 'admin:index' %}">Admin</a></li>

	      {% if user.is_authenticated %}
	      <li><a href="{% url 'userLogin:user_logout' %}">Logout</a></li>
	      {% else %}

	      <li ><a href="{% url 'userLogin:user_login' %}">Login</a></li>
	      {% endif %}


	    </ul>
	  </div>
	</nav>	
	{% block body_block %}
	<div class = 'container'>
		<div class="jumbotron">
			<h2>This is our INDEX page.</h2>
		</div>
	</div>
	{% endblock %}

</body>
</html>

templates/userLogin/login.html
<!DOCTYPE html>
{% extends 'userLogin/index.html' %}

{% block body_block %}
<div class="container">
	<div class="jumbotron">
		<h1>Please Login</h1>
		<form action="{% url 'userLogin:user_login' %}" method = 'post'>
			{% csrf_token %}
			<label for = 'username'>Username:</label>
			<input type="text" name="username" placeholder="Enter username">
			<br><br>
			<label for = 'password'>Password:</label>
			<input type="text" name="password" placeholder="Enter password">
			<br><br>
			<input type="submit" name="" value = 'Login'>
			
		</form>
	</div>
</div>

{% endblock %}

templates/userLogin/thanku.html
<!DOCTYPE html>
{% extends 'userLogin/index.html' %}

{% block body_block %}
	<div class="jumbotron text-center">
		<h1 class="display-3">Thank You!</h1>
		<p class="lead"><strong>Please check your email</strong> for further instructions on how to complete your account setup.</p>
	 </div>
{% endblock %}